"""Add TischLayout table

Revision ID: 62bb5066a2ab
Revises: 
Create Date: 2025-07-20 16:36:03.594490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bb5066a2ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tisch_layout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tisch_layout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tisch_nummer', sa.INTEGER(), nullable=False),
    sa.Column('pos_x', sa.INTEGER(), nullable=False),
    sa.Column('pos_y', sa.INTEGER(), nullable=False),
    sa.Column('aktiv', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tisch_nummer')
    )
    # ### end Alembic commands ###
